name: "Docs Check"
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: pip install -r docs/requirements.txt
    - name: Build HTML docs
      run: sphinx-build -n -W -b html docs docs/_build
  linkcheck:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: pip install -r docs/requirements.txt
    - name: Check links
      run: sphinx-build -W -b linkcheck docs docs/_build
